# Generated by Django 3.0.4 on 2020-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='action_genre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='adventure_genre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='animation_genre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='comedy_genre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='romance_genre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='thriller_genre',
            field=models.BooleanField(default=False),
        ),
    ]
